### ISSUE TITLE
Is this still being worked on?

### ISSUE THREAD

**Issue by AndreyNazarchuk** [wiez/MyPlot#1]
Really looking forward to this plugin!
:) :smile:

**Comment by AndreyNazarchuk** [comment]
WHHHHYYYYY IIIIIIIIIIII??????????????????

**Comment by 64FF00** [comment]
@AndreyNazarchuk xD

**Comment by AndreyNazarchuk** [comment]
I really want this plugin :D

**Comment by iksaku** [comment]
But we dont maintain it, so sorry

**Comment by AndreyNazarchuk** [comment]
Does @wiez still code pocketmine plugins?

**Comment by iksaku** [comment]
Have you seen him active? 
I don't think so

**Comment by AndreyNazarchuk** [comment]
@iksaku well OK then... Mister Attitude!
But you stopped coding at the same time as @wiez 
Did you two have a fight or something?

**Comment by iksaku** [comment]
I'm still coding plugins.-.
But not this xD

**Comment by AndreyNazarchuk** [comment]
AWWWWWWWWWWWWWWWWWWWWWWW MAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAANNNNNNNNNNNNNNNNNNNNN
This is the plugin that I was waiting the most for :'C
That and @RubberBand

**Comment by 64FF00** [comment]
@iksaku :'(

**Comment by AndreyNazarchuk** [comment]
Hey @64FF00 Is a plugin maker, if he wants to can he take over this plugin?

**Comment by PEMapModder** [comment]
Everyone can, because wies never claimed it or what

**Comment by AndreyNazarchuk** [comment]
@wiez made MyPlot, so he claimed it. @PEMapModder

**Comment by iksaku** [comment]
The only plugins that you can't claim nor make competition are _Official_ ones, the ones made by the PocketMine-MP team and MARKED as Official :P

**Comment by PEMapModder** [comment]
No, not worldeditor :P

**Comment by AndreyNazarchuk** [comment]
Can some one please take over and update it then??? This plugin would be
really useful.

**Comment by iksaku** [comment]
Thats a special case xD 

~ Jorge González

**Comment by caingaroo** [comment]
Um iksaku hehehe your the only one that i know on github or member thats staff on prison.megape well the think is there a lovely suprise on the server for the staff 😂😂😂and just to let you know the server was raided somehow theres lava and water and blocks placed all over spawn your the only one i know that can fix this ;-; and i would have went to the kik communite but it wont let me in its full !!
