### ISSUE TITLE
Trees can grow outside plots

### ISSUE THREAD

**Issue by wiez** [wiez/MyPlot#10]
When you place a tree at the edge of a plot, the leaves can grow outside the plot.

**Comment by fycarman** [comment]
Same with water,if you make a pillar and place water,it can go outside the plot. (Sorry for my english but i'm italian)

**Comment by AndreyNazarchuk** [comment]
Make barriers taller, since people can probably fly anyways if its being
used in a creative server.

**Comment by Exxarion** [comment]
We could cancel the water/lava flow event, and I'm still thinking of a way to fix the tree bug.

**Comment by AryToNeX** [comment]
TNT can damage roads! Tested in test server

**Comment by Kelton01** [comment]
Just turn make your server peacefull. that way no one can get gun powder to craft tnt.

**Comment by AndreyNazarchuk** [comment]
Good idea.

**Comment by AryToNeX** [comment]
Plots are used in creative. TNT is in creative mode. Peaceful or not, TNT can damage plots and roads

**Comment by Kelton01** [comment]
I'm using my plots in survival. Just add minereset to get ores and other blocks

**Comment by AndreyNazarchuk** [comment]
Just get a plugin that disables TNT...

**Comment by wiez** [comment]
The TNT bug is fixed more than a week ago by disabling TNT explosion. This issue is about tree that can grow outside plots, which isn't fixed yet.

**Comment by AndreyNazarchuk** [comment]
Aren't there paths between plots? This will keep the trees from reaching
other plots

**Comment by wiez** [comment]
> Aren't there paths between plots? This will keep the trees from reaching
> other plots

Yes but when someone resets a plot, the leaves that are outside the plot won't be reset.

**Comment by AndreyNazarchuk** [comment]
Oh, but the leaves don't grow through barriers so make a glass barrier
around each plot.

**Comment by wiez** [comment]
This is 'fixed' now. You can no longer use bonemeal on trees that are too close to the edge of a plot. 458af658702fcf0260cce99073b5bcded059f204
