### ISSUE TITLE
Failed generating

### ISSUE THREAD

**Issue by xXMarlonJrXx** [wiez/MyPlot#100]
I generate a new plot world .The plotfloor is made of stone and the road is made of coal block.Ive tried to edit the config.yml but it generated the same world

**Comment by jasonwynn10** [comment]
alot of things are currently broeken, what type of server are you running?

**Comment by xXMarlonJrXx** [comment]
I just getting started making a server. Its running for 0.14.2 Mcpe PHP7

**Comment by xXMarlonJrXx** [comment]
Genisys

**Comment by Jorti1** [comment]
I've tried using the system but I was never able Roger it to work. IM not
sure if it would effect the plugin or  not. Have you tried using
pocketmine? [With the .phar file from clearsky.]

**Comment by Jorti1** [comment]
Was never able to get it to work*

**Comment by xXMarlonJrXx** [comment]
Done

**Comment by jasonwynn10** [comment]
Keep in mind, this plugin isn't for php5 Genesis or IM

**Comment by jasonwynn10** [comment]
Php7***
