### ISSUE TITLE
Plots are have no protection on genisys 0.15...

### ISSUE THREAD

**Issue by MasterlazorX** [wiez/MyPlot#101]
Players that are not OP can grief anything and there is no protection...

**Comment by HostingItAll** [comment]
... firstly that is a bug in 0.15 not this plugin, secondly this plugin only officially supports PocketMine and not the other variants.  Please review the issues list on the Genisys page.

**Comment by NML32** [comment]
My users can place items on the road but not break the road. Is this a Genisys issue as well?  If so I'll go report it to Genisys.

**Comment by jasonwynn10** [comment]
As said in @HostingItAll 's post, this page only gives support for pocketmine

**Comment by NML32** [comment]
Plots plugin is working great for me.

**Comment by MasterlazorX** [comment]
Well, Genisys did alot of fixes on 0.15. Ill give it a try, but im expecting to just run it on pm.

**Comment by MasterlazorX** [comment]
Worked, but after i restarted the server, i still had issues. PM is dead, too many crashes and issues.

**Comment by Aericio** [comment]
Use ClearSky ;)

**Comment by jasonwynn10** [comment]
PocketMine's php7 release is faster than clearsky currently

**Comment by jasonwynn10** [comment]
https://github.com/jasonwynn10/MyPlot that is the most updated version of this plugin currently

**Comment by Aericio** [comment]
PocketMine is definitely more stable and releases faster, but they aren't that active.
