### ISSUE TITLE
clearing a plot in 0.15

### ISSUE THREAD

**Issue by isoz** [wiez/MyPlot#103]
Doesn't work, I see an animation going over the terrain but it doesn't clear any block.

**Comment by Aericio** [comment]
Plots don't clear for me, shows an error.

**Comment by jasonwynn10** [comment]
what server platform are you running?

**Comment by jasonwynn10** [comment]
https://github.com/jasonwynn10/MyPlot that is the most updated version of this plugin currently

**Comment by wiez** [comment]
Is the issue solved? Seems to work just fine here
