### ISSUE TITLE
World Plot Clearing

### ISSUE THREAD

**Issue by BobbyTowers** [wiez/MyPlot#105]
Is there anyway you can add a command to clear all the plots in the world with out clearing the spawn plot?

**Comment by jasonwynn10** [comment]
That would cause too much lag for any server, you are better off making a new world

**Comment by Aericio** [comment]
Use (if you have) WorldEdit and copy the spawn, then paste it in the new world. If your spawn is big, enjoy waiting a few minutes for it to load, or crash the server.

**Comment by jasonwynn10** [comment]
https://github.com/jasonwynn10/MyPlot that is the most updated version of this plugin currently

**Comment by wiez** [comment]
This isn't and won't be implemented. I'm sorry
