### ISSUE TITLE
About the limit and use of the Plot

### ISSUE THREAD

**Issue by Wshape1** [wiez/MyPlot#107]
Author: hello, I am a tourist from China, in PocketMine saw your plugin baidu post bar, all came to a dead simple web site to see your plugin, but at the time of use, loading the plugin is invalid, I don't know is my PHP version is too old or plugin problem, I hope you can give us a stable reply, my client PHP version is 5.6, thank you. Then there is this plug-in can limit the number of the Plot, how to use?

**Comment by Wshape1** [comment]
Hope to answer.

**Comment by Wshape1** [comment]
If the plug-in is PHP7, I hope you can get that the plug-in PHP5.6 instead. thank you
Email address: wuxing233@qq.com

**Comment by jasonwynn10** [comment]
this plugin is for the newest version of PocketMine only

**Comment by Wshape1** [comment]
Thanks

**Comment by jasonwynn10** [comment]
I have the downgraded version [here](https://github.com/jasonwynn10/MyPlot) for you. It has a few modifications, but otherwise it's the same.
