### ISSUE TITLE
Players cannot place blocks

### ISSUE THREAD

**Issue by BudderSticks** [wiez/MyPlot#115]
Latley. I have noticed when a player claims a open plot they cannot place or break blocks in it. I have checked permissions, errors and console and everythng. I have even tried to re install the plugin and no change.

Running Genisys MCPE 0.15.10 2.0.0 PHP7

**Comment by jasonwynn10** [comment]
1. MyPlot isn't for 3rd Party servers
2. What version of the plugin are you using?
3. This repo has been discontinued, please use the supported one [here](https://github.com/jasonwynn10/MyPlot)

**Comment by BudderSticks** [comment]
What do ÿou mean 3rd party servers. Plus can you dend me the latest version?

**Comment by jasonwynn10** [comment]
Genesis isn't an original server software, it is just forked from PocketMine-MP and has no support from this repo. Also, the latest version is still in development, so I wouldn't recommend using it yet.

**Comment by BudderSticks** [comment]
okay

do you have any idea how to fix this though?

**Comment by jasonwynn10** [comment]
if there were a debug output, then maybe but as it stands, I can't because I don't have any relative information and your server is the only on experiencing this issue as of now

**Comment by BudderSticks** [comment]
Okay maybe it is anther pligin doing it! Thanks!

**Comment by Jorti1** [comment]
I'm not a developer although this has happened to me in past versions of
myplot & pocketmine. Sometimes, if you have spawn protection enabled
through pocketmine (or Genesis), it goes to all worlds. So if the player
claimed close to spawn or in spawn range, they will not be able to build.
If there is a spawn (in a separate world) you can use plugins to just
protect that world, allowing players to build in the plot world.
