### ISSUE TITLE
Plot world can't generate in Genisys-ITX core

### ISSUE THREAD

**Issue by bzdnd** [wiez/MyPlot#123]
Please update to 3.0.0API and change the map format to MCA

**Comment by jasonwynn10** [comment]
a. this plugin is for PocketMine-MP software only
b. this repository has been inactive for the past year
c. this plugin doesn't set the map format type

**Comment by bzdnd** [comment]
But now PocketMine only supports MCA in the core of the 1.0.0 version....

**Comment by jasonwynn10** [comment]
This repository is still inactive, so you can't really get any help here
