### ISSUE TITLE
Plot World

### ISSUE THREAD

**Issue by Timm03** [wiez/MyPlot#13]
Hi

When i make /p generate Plots   is th server very hard lagging and not generate the world Please help me 

thanks LG  Tim

**Comment by Timm03** [comment]
Haat is the Problem please help me sorry for bad english

**Comment by Timm03** [comment]
what*

**Comment by wiez** [comment]
When you use  "/p generate <name>" it doesn't generate any chunks yet. So the first time you spawn in the world it can take a long time, depending on how fast your server is. I might let the server generate some chunks initially in the future, so it doesn't take so long when you first join the server.

When you spawn into the world the client may freeze for a couple seconds when you place a block because of some light glitches. I'm trying to fix that.

**Comment by Timm03** [comment]
Okay Thanks for Your Answer

Can you make this for me ? I give You ftp details from My Server okay Your
Plugin is nice ;)))))
Am 13.08.2015 11:25 schrieb "Wies" <notifications@github.com>:

**Comment by Timm03** [comment]
Can You this Please Make for me its so nice ;)) Your Plugin When all bugs
fixed i can donate to you later

Lg Tim
Am 13.08.2015 11:31 schrieb "Gurkensaft LP" <timm485@gmail.com>:

**Comment by Timm03** [comment]
And  I am The Owner From BuildMyTown ip BuildMyTown.de
Port 19132
Am 13.08.2015 11:50 schrieb "Gurkensaft LP" <timm485@gmail.com>:

**Comment by wiez** [comment]
This github issue tracker is for bugs of MyPlot only. If you want to talk about anything other than that, contact me or @Exxarion on PocketMine Forums.

**Comment by Timm03** [comment]
I Dont have a Pocketmine Account  sorry but have you kik or WhatsApp App My
Nummber 017631621285 pls contact me on WhatsApp ok ?
Am 13.08.2015 13:22 schrieb "Wies" <notifications@github.com>:

**Comment by RocoWayne** [comment]
im trying /generate myplot (if i use /p generate i set a waypoint for Cameraman plugin , conflict of commands) and the world generate is a survival , with mountains and those kind of things

**Comment by wiez** [comment]
Plot worlds cannot be generated without the myplot command yet. `/p` is an alias for the command `/plot`. So you can use `/plot generate myplot` then. If it would still conflict with one of your other commands. You can change the command name of myplot in the language files (resources/eng.ini).

**Comment by RocoWayne** [comment]
im testing with /generate myplot and the world generated is a usual survival map. It does not generate a plot world with roads and plots. What im doing wrong?

**Comment by wiez** [comment]
> im testing with /generate myplot and the world generated is a usual survival map. It does not generate a plot world with roads and plots. What im doing wrong?

As I already said, it can only be generated with the myplot command

**Comment by RocoWayne** [comment]
Wich is /p generate? 

because i was using the /generate WORLD of the Wiki

**Comment by wiez** [comment]
> Wich is /p generate?
> 
> because i was using the /generate WORLD of the Wiki

/generate is a pocketmine built-in command. And as I already, plot worlds can only be generated with the myplot command. So use /p or /plot

**Comment by RocoWayne** [comment]
done, is was other plugin problem.

**Comment by Timm03** [comment]
Can you send me the phar from the Plugin i need this

2016-01-26 18:56 GMT+01:00 RocoWayne <notifications@github.com>:

**Comment by RocoWayne** [comment]
@Timm03  download the zip and use http://pmt.mcpe.me/
