### ISSUE TITLE
Plot building/protection bug.

### ISSUE THREAD

**Issue by BobbyTowers** [wiez/MyPlot#14]
After a player claims a plot, they can only build on half of the plot. The other half of the plot is still protected. I'm using the latest version of the plugin. PocketMine  build #1258.

**Comment by BobbyTowers** [comment]
It's was my fault.

**Comment by Vaivez66** [comment]
Whats fault?

**Comment by Exxarion** [comment]
@Vaivez66 Please stop commenting on old, closed issues.

**Comment by miroemad** [comment]
hey i want to download this plugin
