### ISSUE TITLE
Trouble installing plugin

### ISSUE THREAD

**Issue by Kelton01** [wiez/MyPlot#15]
I uploaded the plugin to my plugins folder and unziped it but when i restart my server it wont show up in the /plugins list and none of the commands work. is there another way to download this?

**Comment by AndreyNazarchuk** [comment]
If you want to run it you have to use DevTools to run it or use DevTools to
compress it into a .phar

**Comment by Kelton01** [comment]
Thanks it works now.

**Comment by AndreyNazarchuk** [comment]
No problem
