### ISSUE TITLE
Signs don't get removed when the plot is clear/reset. 

### ISSUE THREAD

**Issue by BobbyTowers** [wiez/MyPlot#16]
When I reset/clear the plot. The signs remain in the plot and when you try to manually remove them(hit the sign), its like the sign isn't there. The only way I can remove the sign is to replace the sign in the same place and then hit the sign it will remove them. Its like the sign is invisible.

**Comment by wiez** [comment]
I can't replicate this bug, but I've seen some weird leftover signs when teleporting to a plot world from an other world. I'll look into it.

**Comment by AndreyNazarchuk** [comment]
Recalculate tiles.

**Comment by miroemad** [comment]
i want to get this plugin but the api is old

**Comment by Exxarion** [comment]
It is not old, it works fine on stable builds. Though it is untested on Pocketmine 1.6.

**Comment by miroemad** [comment]
caan someone tell me how to install it on pocket mine 1.5dev

**Comment by wiez** [comment]
This is not an issue anymore, I think
