### ISSUE TITLE
Bug and Requests

### ISSUE THREAD

**Issue by AryToNeX** [wiez/MyPlot#17]
Bug: Helpers can't edit a plot

Requests: Can you add a command which teleports a player to a plot of another player? And can you add plot world editing permission for OPs?

**Comment by wiez** [comment]
I just tried it, and helpers can edit a plot. The addhelper command is case sensitive, so check if the helper name is correct.
Yes I'm planning on adding a tp command.
There is already a permission called "myplot.admin.build" that allows players to build everywhere.
