### ISSUE TITLE
Sometimes plot worlds aren't recognized

### ISSUE THREAD

**Issue by AryToNeX** [wiez/MyPlot#18]
![screenshot_2015-08-23-16-05-44](https://cloud.githubusercontent.com/assets/13177694/9428561/ceb733c2-49b2-11e5-9282-75d2cc7872ed.png)

**Comment by wiez** [comment]
It's probably caused by one of these 3 things: you generated the world with something else than the "/p generate" command, the worlds level.dat file got corrupted (unlikely), or you messed up the worlds configuration file.

**Comment by AryToNeX** [comment]
I generated the world with /p generate in a test server (No other plugins) and I installed MyPlot without modifying configs

**Comment by wiez** [comment]
If you don't have any other plugins, how did you teleport to the world then?

**Comment by Exxarion** [comment]
Also be sure that the plot worlds are loaded on startup. Use pocketmine.yml to do this.

**Comment by AryToNeX** [comment]
@wiez I've "/p generate"d level "creative", shutted down the test server, modified default world to "creative" world in server.properties, restarted the server and rejoined the server. @Exxarion In this method creative world should be loaded on startup
