### ISSUE TITLE
Error with steadfast2

### ISSUE THREAD

**Issue by patrickt1220** [wiez/MyPlot#19]
Im trying to run this plugin on SteadFast2 but I'm getting the following error:

Fatal error: Declaration of MyPlot\MyPlotGenerator::init() must be compatible with pocketmine\level\generator\Generator::init(pocketmine\level\generator\GenerationChunkManager $level, pocketmine\utils\Random $random) in C:\Users\Desktop\PocketMine-MP\plugins\MyPlot-master\src\MyPlot\MyPlotGenerator.php on line 0

any help?

**Comment by wiez** [comment]
It's not our problem if steadfast isn't stable or uses a different api.
