### ISSUE TITLE
Players cant build!

### ISSUE THREAD

**Issue by Vaivez66** [wiez/MyPlot#20]
I have an issue were player (not op) can not build or break something on their plot....is it a bug?

**Comment by Vaivez66** [comment]
And i using pm soft 245

**Comment by Exxarion** [comment]
Be sure that they have claimed the plot and that there is no world protection on.

**Comment by Vaivez66** [comment]
I found the problem....if i uninstall Iprotector from @LDX its work fine....but i protect lobby world, not plot world

**Comment by Exxarion** [comment]
Try using WorldProtect to see if that fixes your issue.
