### ISSUE TITLE
how to install this plugin on pocket mine 1.5 dev

### ISSUE THREAD

**Issue by miroemad** [wiez/MyPlot#21]
api isnt compactible or not please help i really need help

**Comment by miroemad** [comment]
help me i want to know how to install on pocket mine 1.5 dev

**Comment by iksaku** [comment]
Please stop spamming, this plugin is not finished nor ready for usage in "production servers"...

**Comment by miroemad** [comment]
i am not spamming

**Comment by miroemad** [comment]
and i am trying to get it ready
and also alot of servers use this plugin

**Comment by miroemad** [comment]
amd the plugin is ready are you a part of the team
of the devlopers who made the plugin

**Comment by iksaku** [comment]
Yes, posting 2 "similar" posts almost at the same time, with the same content, context and question/answer before other reply is classified as "spamming" :P

Also, _You're not getting it ready_, if you want it, code it by yourself, **don't** try to rush the dev

**Comment by miroemad** [comment]
ok ok
i will make it for my self
and i am going to talk to another devloper to ask him

**Comment by miroemad** [comment]
ii am leaving thread open i need help to install it on pocketmine 1.5

**Comment by iksaku** [comment]
It's okay :D

**Comment by miroemad** [comment]
sorry this is not an isue anymore
