### ISSUE TITLE
Pocketmine 1.6 support

### ISSUE THREAD

**Issue by Exxarion** [wiez/MyPlot#23]
After testing this plugin on Pocketmine 1.6, it seems that players are able to build/destroy on other peoples (or even unclaimed) plots. This could be a big issue for 1.6 servers who want plots.

**Comment by Vaivez66** [comment]
I'm not facing that problem on my server (1.6)

**Comment by Exxarion** [comment]
Nevermind, i was using a modified, development version of the plugin.
