### ISSUE TITLE
Biome

### ISSUE THREAD

**Issue by Vaivez66** [wiez/MyPlot#25]
I use this plugin on pm 1.6 bleeding build 48, and I change biome on my plot, and guess what? Only a part of my plot were biome changed! I don't know is a pm bug or this plugin...

**Comment by Vaivez66** [comment]
![screenshot_2015-10-16-10-49-48](https://cloud.githubusercontent.com/assets/13620616/10533470/f50405f8-73f3-11e5-9a9b-511102a063f2.png)

**Comment by iksaku** [comment]
This is due to "Chunk" biomes... Something can be done... But hackly :P

**Comment by Vaivez66** [comment]
Nvm, it happen because I configure pocketmine.yml incorrectly
