### ISSUE TITLE
Payment is not done successfully

### ISSUE THREAD

**Issue by HerO-0110** [wiez/MyPlot#26]
As the title suggests, players' money is not checked properly, resulting in the error message. I'm not quite sure how the function was done on the code, but most people uses economys, and would be best if you simply do EconomyAPI::mymoney($player) to get players' money for now as a temporary fix.

**Comment by wiez** [comment]
Sorry that fix didn't fix anything. I'll have to test it first.

**Comment by HerO-0110** [comment]
$price = $this->config->getAll()["DefaultWorld"]["ClaimPrice"];
if (EconomyAPI::getInstance()->myMoney($sender) < $price) {
            $sender->sendMessage(TextFormat::RED . "You don't have enough money to claim this plot");
            return true;
        }
Try this. I am not quite sure how to retrieve value from the config, so don't use the way I defined $price if it is wrong.

**Comment by HOSTMARCEL** [comment]
i see your from belgium? i'm from the netherlands!
your plugin and my server will make generations unite.
i wonder if i can use this on a custom plot map?
skype HostMarcel maybe you can do something for a fee i want to run  hudge plot server
let me know

**Comment by wiez** [comment]
Just fixed a bug that might be related to this 67b972390558c9ba3b609252234877d71cee22b5.
When the price of a plot was set to zero, it always said that you didn't have enough money.

Keep in mind that changing the price in config.yml doesn't have any effect on worlds that are already generated. The prices in each world can be changed in the plugins/MyPlot/worlds/ folder.
