### ISSUE TITLE
plot bought but unable to edit after

### ISSUE THREAD

**Issue by HOSTMARCEL** [wiez/MyPlot#27]
when i buy the plot and i check with /p info it shows i have bought the plot, but i cannot edit it O-o
i dont have any plugin besides EconomyAPI_v2.0.9
please help :)

**Comment by HerO-0110** [comment]
I didn't managed to recreate this error. Let's see what @wiez have to say about this.

**Comment by wiez** [comment]
Seems to work fine for me. Maybe you bought a plot in the spawn area and enabled spawn protection?

**Comment by HOSTMARCEL** [comment]
#closed it had to do something with the minecraft itzelf...after using a newer build the problem was gone thanks for the quick reply's and support!
