### ISSUE TITLE
Where is the .phar?

### ISSUE THREAD

**Issue by SoyPro** [wiez/MyPlot#31]
Can you help me? I want this plugin,i downloaded the zip but where is the myplot.phar?

**Comment by AndreyNazarchuk** [comment]
You have to make it.

**Comment by SoyPro** [comment]
But how?

**Comment by SoyPro** [comment]
I need this for my server,players ask me for a plugin call myplot.can you explain me how to create a .phar?

**Comment by SoyPro** [comment]
Why the owner of this plugin doesnt make the .phar.he has to public un pocketmine-mp!

**Comment by AndreyNazarchuk** [comment]
Because he does not have time to do something that easy.
Just download devtools, extract the MyPlot folder into the plugin folder,
start the server and then type "makeplugin MyPlot"

**Comment by Exxarion** [comment]
This plugin is unfinished. Once it is completed, we will create a .phar.
