### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by iDirtniverse** [wiez/MyPlot#32]
Admin cant access any plot or delete or edit with other land unless they claim could you add features where admin can access every block? .admin?

**Comment by Exxarion** [comment]
Use PurePerms to add the admin permissions to your admin groups.

**Comment by iDirtniverse** [comment]
Is there an update for perm? like is perm for admin exisist?

**Comment by Exxarion** [comment]
myplot.admin is the admin permission node.

**Comment by iDirtniverse** [comment]
Thank you :+1
