### ISSUE TITLE
Please quit the pvp,players can buy lands,there isnt protection in chests,players can open others chests,etc

### ISSUE THREAD

**Issue by SoyPro** [wiez/MyPlot#36]
Players can PvP in plots and they can open others chests in plots and they can buy a land with /startp and /endp and then /land buy,but they can buy lands in the path wood and fix all the bugs because the console show me that your plugin have a lot of bugs

**Comment by Thunder33345** [comment]
well it is just block protection(you cant open and close stuff)
you should somehow disable /land on the plot world

**Comment by Exxarion** [comment]
You can disable /land with PurePerms (multi-world permissions)

**Comment by SoyPro** [comment]
But please quit the pvp

**Comment by Jelly9912** [comment]
Use WorldProtect plugin and write /pvp-off or something like this

**Comment by SoyPro** [comment]
Pureperms multiworld doesnt work,it throw me an error,@64FF00 have to fix multiworld

**Comment by wiez** [comment]
It is not the goal of this plugin to handle pvp protection. All your other problems are related to other plugins interfering with MyPlot
