### ISSUE TITLE
plot world inst loaded even player itself is in plot world

### ISSUE THREAD

**Issue by Thunder33345** [wiez/MyPlot#37]
and a request : perm node to load plot world ex autoload world if player have load world perm

maybe caused by #38 (/setworldspawn or /reload)

**Comment by wiez** [comment]
Yes this probably has to do with the /reload bug. Thanks for reporting!

**Comment by Exxarion** [comment]
/reload breaks a lot of plugins, doesn't it?

**Comment by wiez** [comment]
This should be fixed with 8dd69ced9fa4f2f109599f0f4678aaaf4f4ef7ca
