### ISSUE TITLE
"you are not standing inside a plot" even you are in a plot

### ISSUE THREAD

**Issue by Thunder33345** [wiez/MyPlot#38]
after executing /reload it snow that massage
and does /setworldspawn will mess things up or what?
that can or may the the reason of how it causes #37

**Comment by wiez** [comment]
You are using DevTools and loading MyPlot from source, right? DevTools doesn't reload the source plugins when /reload is executed. If you want /reload to work, try MyPlot as a phar file.

**Comment by Thunder33345** [comment]
well i am using pmt.mcpe.me to phar it and after reload /p is still avable but it said you are not in a plot when /p claim and does /setworld spawn mess stuff up?

**Comment by isoz** [comment]
I can confirm this, it somehow breaks the players permissions and players are also able to build in the roads when /reload happens, if I stop the server it fixes it.

I would like to thank wiez and everyone else collaborating on the plugin for the amazing job.

**Comment by CraftingMania** [comment]
generate a new world that will fix it

**Comment by wiez** [comment]
Apparently this is still an issue

**Comment by wiez** [comment]
/reload doesn't reload the worlds. So the LevelLoadEvent will not be called again. Trying to find a workaround...

**Comment by Thunder33345** [comment]
anyway to detect the command /reload is invoked?

**Comment by wiez** [comment]
It should be fixed with 8dd69ce

**Comment by PEMapModder** [comment]
PocketMine plugin standards should assume that the server is in the middle of runtime when loading.

**Comment by Thunder33345** [comment]
thats is just yours option unfortunately

**Comment by PEMapModder** [comment]
@Thunder33345 ?
