### ISSUE TITLE
Same commands and config as PlotMe?

### ISSUE THREAD

**Issue by wiez** [wiez/MyPlot#4]
Currently this plugin is in early development and is different in a lot of things from PlotMe. Would it be a good idea to use (mostly) the same commands and config file as PlotMe? Currently I spend as much time thinking which settings, commands, api, permissions, ... I should implement as I spend time on implementing it and most of the time it turns out that PlotMe uses the most elegant way. We also wouldn't have to put a lot of effort into the documentation because there are already a bunch of tutorials out there how to configure PlotMe.

I would like to know what you guys prefer?

**Comment by AndreyNazarchuk** [comment]
Whatever is better and easier of you :)

**Comment by wiez** [comment]
> Whatever is better and easier of you :)

Well lets go for a PlotMe clone then...
