### ISSUE TITLE
Biomes are missing

### ISSUE THREAD

**Issue by daany123** [wiez/MyPlot#40]
I see that some of the biome that you add to the description in the /p biome command is not running well! That's beacause when i used some of the biome like TAIGA or OCEAN, it didn't work. Please check the problem! Thanks :)

**Comment by PEMapModder** [comment]
Did you know that there is an edit button for you comment so that you don't need to create a new issue?

**Comment by daany123** [comment]
I know but on my device, I don't see that button so I have to make a new issue. Sorry for that!

**Comment by doducquang** [comment]
MOUTAINS biome doesn't work :v

**Comment by wiez** [comment]
MyPlot uses all the built-in biomes of pocketmine. All biomes are working, it will only change the grass color. The grass color of some are identical, so it might be better to remove them.

**Comment by wiez** [comment]
The obsolete biomes are removed now bca261de7e3123d23768197d8f1a7aa498daaa07
