### ISSUE TITLE
Pocketmine 1.13 error

### ISSUE THREAD

**Issue by HerO-0110** [wiez/MyPlot#41]
Declaration of MyPlot\MyPlotGenerator::init() must be compatible with pocketmine\level\generator\Generator::init(pocketmine\level\generator\GenerationChunkManager $level, pocketmine\utils\Random $random)
File: /MyPlot.phar/src/MyPlot/MyPlotGenerator
Line: 205
Type: E_COMPILE_ERROR
I believe this occurred as soon as I updated my server PMMP to 1.13.

**Comment by Exxarion** [comment]
0.13 came out so fast, we haven't even added support for it yet.

**Comment by PEMapModder** [comment]
PocketMine 1.13 isn't 0.13, I think.

**Comment by HerO-0110** [comment]
Yup, I was meant to say MCPE 0.13 :P
So what does this error mean?

**Comment by CraftingMania** [comment]
means you use pocketmine 1.4 not 1.7 there is an unofficia relese of pocketmine 1.7 made test it with my ploy it will work

**Comment by CraftingMania** [comment]
i tried it

**Comment by NguyenQuangLap** [comment]
Someone please just help me running. php is not
