### ISSUE TITLE
How to give plot?

### ISSUE THREAD

**Issue by ghost** [wiez/MyPlot#43]

**Comment by Jelly9912** [comment]
Each player can secure a plot with command /f claim

**Comment by doducquang** [comment]
I mean how can i give my plot to another player (change owner)?

**Comment by Jelly9912** [comment]
You can't, use /f reset or /f dispose and other player can now use /f claim

**Comment by doducquang** [comment]
That's sad :( can you add the /p give command ? :)

**Comment by Exxarion** [comment]
It's /p, not /f

**Comment by iPeedroPvP** [comment]
Hello ? Fast You can help me ? I hum MCPE server and I'm behind hum plug-in portions My friends told You and Developer one, quick Can you give me the dowloand do myplots.phar ? thank 👍

**Comment by astersx** [comment]
*facepalm* just compile it -.-'

**Comment by wiez** [comment]
No need to keep this open. Relevant to request #49
