### ISSUE TITLE
How to setup?

### ISSUE THREAD

**Issue by Jorti1** [wiez/MyPlot#47]
How do we get the plugin working .
What command exact do we use for devtools?
Once I know if I am allowed I will make a video to gelp others

**Comment by Exxarion** [comment]
If you have DevTools, just drag the folder for this plugin into your "plugins" folder. DevTools should auto-load this.

**Comment by Jorti1** [comment]
OK , do we leave the zip , or the file ?

**Comment by PEMapModder** [comment]
You can try this http://forums.pocketmine.net/threads/zippluginloader.8924/

**Comment by wiez** [comment]
I assume you figured it out already, so I'm closing this "issue".

**Comment by Jorti1** [comment]
Yes ,I have thx
