### ISSUE TITLE
New Commands

### ISSUE THREAD

**Issue by Exxarion** [wiez/MyPlot#54]
New commands to be added to MyPlot:

- [x] /p give \<player> - Give your plot to someone else

- [x] /p warp \<x;z> - Teleport to a plot

**Comment by iPeedroPvP** [comment]
Hello ? Fast You can help me ? I hum MCPE server and I'm behind hum plug-in portions My friends told You and Developer one, quick Can you give me the dowloand do myplots.phar ? thank 👍

**Comment by Aericio** [comment]
iPeedroPvP, get DevTools and put the plugin information into DevTools and do /makeplugin MyPlot. Then go back to the DevTools folder and bring our MyPlot_v1. I'll send you a link to download the .phar  to make it easier for you. https://www.dropbox.com/s/s18y3wi4tjtg04u/MyPlot_v1.phar?dl=0

**Comment by astersx** [comment]
This plugin is awesome,  it dont need to be edited!!!  Good Job :+1: ,  is just that /p generator is not only for ops,  and pureperms can fix it but in plugins list show inactive so i wonder for how long time pireperms will work (new pocketmine api etc....)

**Comment by wiez** [comment]
*/p enter* will require a change in the database structure (extra field) and is a backward incompatible change.

**Comment by astersx** [comment]
The plugin dont need new comands!!  i will not update i will keep the old plugin forever :p,  is perfect,  no need changes :+1:

**Comment by Exxarion** [comment]
Well, that is true. Guess that command will be scraped.

**Comment by wiez** [comment]
I've implemented `/p warp <x;z>` so I'm not sure if `/p goto <player>` is needed anymore.

**Comment by Exxarion** [comment]
<addr>/p goto</addr> was used to goto another player's plot, but I guess players can tell others their plot ID
