### ISSUE TITLE
plot home

### ISSUE THREAD

**Issue by astersx** [wiez/MyPlot#55]
/plot home number dont work
my plot number (4;0)
i tryed /plot home 0,  /plot home 4;0, /plot home 4....  And more 
Still no work,  please tell me how to do it :(

Thank you in  advance 😊

**Comment by Jelly9912** [comment]
Use /plot home 1

**Comment by astersx** [comment]
Thx that was helpfull

**Comment by M4nt0s** [comment]
How ro install this Plugin.? Where i can install it. It is awesome!!!

**Comment by M4nt0s** [comment]
How ro download this Plugin. (MyPlot)
Am 08.01.2016 17:46 schrieb astersx <notifications@github.com>:Closed #55.
