### ISSUE TITLE
plot generate 

### ISSUE THREAD

**Issue by Tolo0** [wiez/MyPlot#56]
All players can use /p generate. It should be op only.

**Comment by CraftingMania** [comment]
this is fixed in with pull request #53 you should update your compile a new phar

**Comment by CraftingMania** [comment]
download zip and use dev tools to make it phar and after that delete your current phar and upload the new one

**Comment by Tolo0** [comment]
Ok thanks.  I found a new problem.  When adding a Helper to ur plot. They can't build on it.

**Comment by CraftingMania** [comment]
sometimes work and sometimes makes this problem with me too

**Comment by wiez** [comment]
> Ok thanks. I found a new problem. When adding a Helper to ur plot. They can't build on it.

Works fine for me. Do you have any other plugins that might interfere?
