### ISSUE TITLE
Helpers can't move to plots

### ISSUE THREAD

**Issue by XiangZhao969** [wiez/MyPlot#59]

**Comment by Exxarion** [comment]
Can you be a bit more descriptive? I can't address the problem until I know exactly what is wrong.

**Comment by XiangZhao969** [comment]
I mean helpers can't teleport to plots's which they are invited. there is no command to do that

**Comment by Exxarion** [comment]
That is not possible for anyone yet. I am planning to add a command that will teleport you to the plot ID of your choosing.
