### ISSUE TITLE
/p auto broken and reload bug

### ISSUE THREAD

**Issue by patrickt1220** [wiez/MyPlot#6]
/p auto doesnt work. Just says there are no free plots in the world.  Also when my server reloads plot world is unprotected!  Just letting you know in case you werent aware.  Great job so far!  The plugin works great other than those two bugs.

**Comment by wiez** [comment]
Thank you for reporting this bug! The auto command should be fixed now.
The reload bug is a bug with devtools. You'll have to create a phar file of MyPlot plugin for the reload command to work.

**Comment by patrickt1220** [comment]
Thank you very much! :+1:

**Comment by Vaivez66** [comment]
How to create phar

**Comment by AryToNeX** [comment]
@Vaivez66 look pmt.mcpe.me
