### ISSUE TITLE
About language

### ISSUE THREAD

**Issue by Adam1609** [wiez/MyPlot#64]
Is there any chance that vietnamese will be translate? Since you updated myplot i cant use vietnamese translation anymore!! pls help

**Comment by Exxarion** [comment]
The old translation file is outdated. If you want to, you can help translate it by translating the English file and making a pull request.

**Comment by RocoWayne** [comment]
Sorry about this, but how can i get in touch with you @wiez ? We have a VERY successfull server with myplot running and i wanna show you!

**Comment by Exxarion** [comment]
@RocoWayne, you can contact either of us on the Pocketmine forums.

**Comment by NguyenQuangLap** [comment]
Translate MyPlot very easy, for me it's normal too :)

**Comment by Exxarion** [comment]
The Vietnamese language pack has been updated.
