### ISSUE TITLE
players can't build on ther plots

### ISSUE THREAD

**Issue by Tolo0** [wiez/MyPlot#68]
I keep getting complaints from players saying they can't build on ther plot that they bought weeks ago.

**Comment by MCPEPIG** [comment]
Are you using WorldProtect?

**Comment by Tolo0** [comment]
Yea but the plot world isn't protected or locked.

**Comment by Driesboy** [comment]
spawn place protect

**Comment by Driesboy** [comment]
i dont have this problem and i use the newest version
i have test it for IM,Clearsky,Genisys and PocketMine
