### ISSUE TITLE
Not Load World

### ISSUE THREAD

**Issue by kdani1** [wiez/MyPlot#7]
Hi I Think Your Idea is Great!
But if i generate a world, I Cant load it i Dont Know its a Bug Or I Have to wait more time. Can You Look after it? Thank you :)

**Comment by wiez** [comment]
The "/p generate <name>" command only generates a new world, it doesn't teleport you to the world. You will need an other plugin to teleport to the world like SignWarp. You could also use the "/p auto" command which will teleport you to a free plot, but to use this command at least one plot world has to be loaded. In the file pocketmine.yml there is a "worlds" section and you can list all the worlds that you want to be loaded at startup.

**Comment by RocoWayne** [comment]
you need to Tp yourself to that world... /mw tp WORLDNAME
