### ISSUE TITLE
Can you add /p deny?

### ISSUE THREAD

**Issue by SoyPro** [wiez/MyPlot#70]
For quit players that are boring in your Plot you can put /p deny <name> and that Player will be teleported oitside the plot, make sure put something to block player from entering the plot again.

**Comment by Exxarion** [comment]
As in Plot bans?

**Comment by SoyPro** [comment]
Something like that.do you ser the pc version? PlotMe? There is a command /p deny its for kick a player from entering the plot

**Comment by jasonwynn10** [comment]
#75 & #76 are good starts for this

**Comment by Exxarion** [comment]
Done.

If you use /p private, only the owner and the helpers can enter the plot. This can be reverted by using /p public.
