### ISSUE TITLE
Some problems

### ISSUE THREAD

**Issue by pilock** [wiez/MyPlot#72]
players name use upper case or lower case
for example
steve,Steve,sTeve
He could get more than two pieces of plots.
My English is not very good, should be able to see to understand

**Comment by jasonwynn10** [comment]
this wouldn't work with the way pocketmine does their username checking. The players username is always checked as all lowercase.

**Comment by Exxarion** [comment]
Pocketmine is not case sensitive when checking usernames. This is not fixable.
