### ISSUE TITLE
Public Plots

### ISSUE THREAD

**Issue by jasonwynn10** [wiez/MyPlot#73]
Can there be a command added that will make a plot public? I have a server that uses this plugin, but the mine can't be used as the plot isn't public. If this command were implemented, I would be grateful.

**Comment by jasonwynn10** [comment]
Also, if there could be a makeprivate subcommand to revert the plot back, that would be great of you.

**Comment by jasonwynn10** [comment]
I'm not sure if my pull request #74 is all that was needed to work...

**Comment by Exxarion** [comment]
Done

**Comment by jasonwynn10** [comment]
what is the default?
