### ISSUE TITLE
Please add ItemFrame protection support.

### ISSUE THREAD

**Issue by jerryzooyoyo** [wiez/MyPlot#88]
When you put an item into an ItemFrame, others can steal it.
( even you don't give anyone the helper permisson )

More Infomation: I use Genisys.

**Comment by Vaivez66** [comment]
The short description says:
Plot and protection plugin for **PocketMine**

**Comment by Jorti1** [comment]
@Reziq Vavai Where does it say this & what does it mean?

**Comment by Vaivez66** [comment]
![screenshot_2016-05-03-12-02-02](https://cloud.githubusercontent.com/assets/13620616/14975000/ea4fc2a2-1126-11e6-8e5e-1039ccbc12ad.png)

**Comment by jasonwynn10** [comment]
Because this plugin is for PocketMine and not other third party software, myplot  cannot do this since PocketMine doesn't support Item Frames Yet.

**Comment by Exxarion** [comment]
We made this plugin specifically for PocketMine, and Pocketmine only. We have not tested it on other platforms, and we do not know if it supports it.

**Comment by jerryzooyoyo** [comment]
Okay, thanks for your help ! =)
You did a great job.
