### ISSUE TITLE
Problems about generating the world

### ISSUE THREAD

**Issue by AryToNeX** [wiez/MyPlot#9]
When I generate a plot world the plugin says that the world is correctly generated but when I teleport into the world that world is empty and I'm freezed into the void and when I shut down the server I have to kill it!

**Comment by iksaku** [comment]
Remember that you need to load it ;)

**Comment by Exxarion** [comment]
It is important to load the world before teleporting to it, and be sure to try using /p auto to see if the plots generated. If all else fails, you can delete the world in your worlds/ folder, and generate a new one.

**Comment by AryToNeX** [comment]
This happened a minute ago. I did
/p generate plot
/mw load plot
/mw tp plot
And I'm freezed into the void
Then I sended /p auto and nothing happened
It just crashed my server and RakLib threads.

**Comment by Exxarion** [comment]
May I see the crash dump?

**Comment by AryToNeX** [comment]
And this is strange... I haven't found crash dumps! *watching server log* Server killed itself, it didn't close normally!

**Comment by Exxarion** [comment]
What plugins do you have installed?

**Comment by AryToNeX** [comment]
MyPlot, SimpleAuth, SimpleAuthHelper, PurePerms, PureChat, iProtector, WorldProtect, LiveSigns, MCG76's BlockHunt, PrizeWin, TapToDo, CustomAlerts, MassiveEconomy, SignShop, Broadcaster, AdvancedMOTD, AFK, SurvivalHive TPA, GrabBag, FactionsPro, ItemCasePE, MagicTelePortal, ManyWorlds, MSpawns, NetherChests, PlanB, PocketGuard, RealTime, SubSigns, TimeCommander, ClearLagg, SimpleWarp, SimpleHome, TimerBan, WorldEditArt

Before MyPlot I had SimpleLandGenerator but now is uninstalled

**Comment by wiez** [comment]
Commit bf00b410655cdbcd43bc20774356e1c31d3e6196 improves world generation a bit. I can't make it any faster. If it takes really "half an hour", then you should invest in a server. The MyPlot demo server (188.166.9.45:19132) runs smoothly on a cheap 512mb digitalocean vps.
