### ISSUE TITLE
QUESTION: How do I install this plugin???

### ISSUE THREAD

**Issue by c0rt3xg4m1ng** [wiez/MyPlot#92]
### I just don't know how to install this plugin but I know how to install Pocketmine plugins

# Please tell me how...

**Comment by Jorti1** [comment]
This is a PocketMine plugin... Download the .zip from github and move it to
your plugins folder, then download zip plugin loader from PocketMine and
start your server, I believe you DO NOT extract the zip.

**Comment by c0rt3xg4m1ng** [comment]
KK ill try...

**Comment by c0rt3xg4m1ng** [comment]
So here's what happened...

`[12:17:06] [Server thread/ERROR]: Could not load plugin 'MyPlot': Incompatible API version
`

**Comment by Jorti1** [comment]
If you don't clearly understand how, ask me because it took me a entire
month until I got it to work, so now I'm here helping others. Also once it
is installed, DO NOT USE MW TO GENERATE THE WORLD! It works but the code
doesn't run properly, do /p {Generate/create} (I don't remember the cmd) so
MyPlot works and detects it as a plot world

BTW I am not a dev nor have any permission by the Owner to help, but I do
it anyways

**Comment by Jorti1** [comment]
Can you send m the crash dump and what API are you running?

**Comment by Jorti1** [comment]
I don't know if Myplot is running php 5 still, last time I used it it was
running that, but many people are starting to update to Php 7

**Comment by c0rt3xg4m1ng** [comment]
Now it has a different error...

-------------------------------------------------------------------------------------------------------------------------------
[17:58:53] [Server thread/INFO]: Enabling ZipPluginLoader v1.2.0
[17:58:53] [Server thread/INFO]: [ZipPluginLoader] Loading zip plugin MyPlot v1
[17:58:53] [Server thread/CRITICAL]: ClassNotFoundException: "Class MyPlot\MyPlot not found" (EXCEPTION) in "/src/spl/BaseClassLoader" at line 144
[17:58:53] [Server thread/INFO]: Disabling ZipPluginLoader v1.2.0
[17:58:53] [Server thread/INFO]: Enabling ZipPluginLoader v1.2.0
[17:58:53] [Server thread/INFO]: [ZipPluginLoader] Loading zip plugin MyPlot v1
[17:58:53] [Server thread/CRITICAL]: ClassNotFoundException: "Class MyPlot\MyPlot not found" (EXCEPTION) in "/src/spl/BaseClassLoader" at line 144
[17:58:53] [Server thread/INFO]: Disabling ZipPluginLoader v1.2.0
-------------------------------------------------------------------------------------------------------------------------------

Pocketmine details:

API: 2.0.0
PHP: 7.0.2
PocketMine-MP.phar: Pocketmine-iTX Genisys
Version: 1.1dev-b5301da
PocketMine Launcher Version: PocketMine-Windows-x86-PHP7-launcher

**Comment by jasonwynn10** [comment]
I think I know the issue....
gimme a sec to see if I can fix it

**Comment by c0rt3xg4m1ng** [comment]
yeah Sure! That would be great! :)

**Comment by yeskyIndo** [comment]
@jasonwynn10 send to me too please :)

**Comment by c0rt3xg4m1ng** [comment]
# GOT IT WORKING FINALLY!
Go here to get the compiled phar: http://www.mediafire.com/download/boa26kcctzd5ccj/Plots_Plugin.phar

**Comment by Jorti1** [comment]
What was wrong?
