### ISSUE TITLE
MyPlots Doesn't work correctly.

### ISSUE THREAD

**Issue by c0rt3xg4m1ng** [wiez/MyPlot#95]
1) /p generate makes a Stone Plot and Coal Road.
2) When you walk on a plot it doesn't Show the Owner Info.
3) Config.yml doesn't work

Please tell me how to fix this.

**Comment by jasonwynn10** [comment]
MCPE 0.14.2 broke the showing of the plots owner's info

**Comment by Jorti1** [comment]
Do you have so me thing that would interfere with the plugin like
broadcaster?

**Comment by c0rt3xg4m1ng** [comment]
I removed Broadcaster and I even tried using it as the only plugin...

**Comment by c0rt3xg4m1ng** [comment]
Please update this plugin for 14.3 to make it work again.

**Comment by jasonwynn10** [comment]
BasicHUD doesn't use the same method of message delivery

**Comment by jasonwynn10** [comment]
The plugin is dependant on whether or not the server that you use has fixed the $player->sendTip() function

**Comment by jasonwynn10** [comment]
It might also be fixed if #91 would be merged

**Comment by Jorti1** [comment]
Where are you getting your .phar files from? imagicalmine? ClearSky?

**Comment by c0rt3xg4m1ng** [comment]
iTX Technologies Genisys

**Comment by Jorti1** [comment]
Would reply but I gtg

**Comment by jasonwynn10** [comment]
this plugin isn't for anything but php5 PocketMine

**Comment by jasonwynn10** [comment]
ClearSky works the best with it currently

**Comment by wiez** [comment]
1) The defaults are changed to grass plot and wooden road again. 4d234d9d92632f8c16beee1cca7bbd46b9ec5890
2) Has been fixed now. d52892dba2d9877cfb241f3b02325c4c2bc72d35
3) I assume you are talking about the world properties? These are used for new generated worlds. If you want to change properties from existing worlds, you'll have to edit the according file in MyPlot/worlds/
