### ISSUE TITLE
Players can't build on their own plots...

### ISSUE THREAD

**Issue by Akuroma** [wiez/MyPlot#96]
Hi. I recognized that normal players, without OP, can't build on their claimed plots. I have no WorldProtection and my SpawnProtection is disabled. Also IProtector is deinstalled. Can you help me?

**Comment by jasonwynn10** [comment]
MyPlot is currently having a lot of issues, it is coming with the 0.14.2 and 0.14.3 releases breaking PocketMine functions

**Comment by Akuroma** [comment]
Now I have downloaded the new version of yours, but non OPs can't build. The "Not standing inside a plot" Bug is gone. But now normal players can't build. Ivealready disabled the spawn protection. And I don't have any protection plugins yet.

**Comment by jasonwynn10** [comment]
https://github.com/jasonwynn10/MyPlot that is the most updated version of this plugin currently
