### ISSUE TITLE
Deprecated: sendTip() should no longer be used

### ISSUE THREAD

**Issue by NML32** [wiez/MyPlot#97]
Deprecated: sendTip() should no longer be used in phar:///home/nml32/pocketmine/PocketMine-MP.phar/src/pocketmine/Player.php on line 3910

I'm getting the above error with the latest Genisys PM build. I was informed sendtip() shouldn't be used anymore.

**Comment by jasonwynn10** [comment]
1. This plugin isn't for php7 Genesis or ImagicalMine
2. It hasn't been worked on for a few weeks
3. The issue is already known here: #91

**Comment by HostingItAll** [comment]
Could easily change all the SendTip to SendPopup and correct the issue in a pull :)

**Comment by NML32** [comment]
Thanks @HostingItAll

**Comment by jasonwynn10** [comment]
@HostingItAll that is what #91 is for

**Comment by wiez** [comment]
#91
