### ISSUE TITLE
You're not standing inside a plot....

### ISSUE THREAD

**Issue by Akuroma** [wiez/MyPlot#99]
When I stand in a plot and I want to clear or reset it it shows the following message: "You're not standing inside a plot.". This happens also when I want to add a helper. Can you help me? This plugin needs really to be updated :(

**Comment by jasonwynn10** [comment]
what type of server are you running?

**Comment by Akuroma** [comment]
ClearSky 1.1 Sunrise. Yesterday it was working perfectly everything was fine. But today it isnt that fine.

**Comment by jasonwynn10** [comment]
The latest version of this plugin isn't really current. I have a download link that I use on my server if you want it

**Comment by Akuroma** [comment]
This would be nice of you :)

**Comment by Akuroma** [comment]
How do I get it?

**Comment by jasonwynn10** [comment]
I'll post a link here in an hour

**Comment by JosiahLeas** [comment]
I'm having the same issue. Did you find a fix?

**Comment by jasonwynn10** [comment]
https://github.com/LostTeam/MyPlot there is the most updated version of this plugin
